version: '3.4'

services:
  weathertest:
    image: ${DOCKER_REGISTRY-}weathertest
    container_name: weathertest
    depends_on:
      - "redis"
    build:
      context: .
      dockerfile: WeatherTest/Dockerfile
    links:
      - "redis"    

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server
    ports:
     - "6379:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master

  requestlogapi:
    image: ${DOCKER_REGISTRY-}requestlogapi
    container_name: requestlogapi
    links:
      - "rabbitmq" 
    depends_on:
      - "rabbitmq"
    build:
      context: .
      dockerfile: RequestLogAPI/Dockerfile


  rabbitmq:
     image: "masstransit/rabbitmq"
     container_name: rabbitmq
     ports:
     - "5672:5672"
     - "15672:15672"

